apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clipp.name" . }}
automountServiceAccountToken: {{ or (eq (include "clipp.watchTCP" .) "true") (eq (include "clipp.watchUDP" .) "true") }}
{{- if or (eq (include "clipp.watchTCP" .) "true") (eq (include "clipp.watchUDP" .) "true") }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "clipp.name" . }}-watch
rules:
  - apiGroups: [""]
    resources: [services]
    resourceNames:
      {{- if eq (include "clipp.watchTCP" .) "true" }}
      - {{ include "clipp.name" . }}-tcp
      {{- end }}
      {{- if eq (include "clipp.watchUDP" .) "true" }}
      - {{ include "clipp.name" . }}-udp
      {{- end }}
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "clipp.name" . }}-watch
subjects:
  - kind: ServiceAccount
    name: {{ include "clipp.name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "clipp.name" . }}-watch
  apiGroup: rbac.authorization.k8s.io
{{- end }}
